/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Currency_Converter;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MyCurrencyConverter extends javax.swing.JFrame {
    
String[] CurrencyUnits = {
"units",
"US Dollar",
"France Euro",
"UK Pound",
"Indian Rupees",
"Pakistani Rupees",
"Japanese Yen",
"Canadian Dollar",
"Russian Ruble"
};
double US_Dollar = 1.21;
double France_Euro = 1.15;
double UK_Pound = 1;
double Indian_Rupees = 101.08;
double Pakistani_Rupees = 336.55;
double Japanese_Yen = 181.57;
double Canadian_Dollar = 1.66;
double Russian_Ruble = 118.61;



    /**
     * Creates new form MyCurrencyConverter
     */
    public MyCurrencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Unknown = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstCountry = new javax.swing.JComboBox<>();
        T1 = new javax.swing.JTextField();
        SecondCountry = new javax.swing.JComboBox<>();
        T2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstCurrencyUnit = new javax.swing.JLabel();
        SecondCurrencyUnit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Unknown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Currency Converter");

        FirstCountry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "United States", "France", "United Kingdom", "India", "Pakistan", "Japan", "Canada", "Russia", " " }));
        FirstCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FirstCountryItemStateChanged(evt);
            }
        });

        T1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SecondCountry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SecondCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "United States", "France", "United Kingdom", "India", "Pakistan", "Japan", "Canada", "Russia" }));
        SecondCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SecondCountryItemStateChanged(evt);
            }
        });

        T2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("From Currency");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("To Currency");

        FirstCurrencyUnit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FirstCurrencyUnit.setText("Units");

        SecondCurrencyUnit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SecondCurrencyUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SecondCurrencyUnit.setText("Units");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Convert Currency");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UnknownLayout = new javax.swing.GroupLayout(Unknown);
        Unknown.setLayout(UnknownLayout);
        UnknownLayout.setHorizontalGroup(
            UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnknownLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UnknownLayout.createSequentialGroup()
                        .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(T1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(FirstCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(FirstCurrencyUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(109, 109, 109)
                        .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UnknownLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(UnknownLayout.createSequentialGroup()
                                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SecondCountry, 0, 335, Short.MAX_VALUE)
                                    .addComponent(T2)
                                    .addComponent(SecondCurrencyUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(89, 89, 89))))
                    .addGroup(UnknownLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)
                        .addGap(121, 121, 121)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(160, 160, 160))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UnknownLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(243, 243, 243))
        );
        UnknownLayout.setVerticalGroup(
            UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnknownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstCurrencyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondCurrencyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UnknownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Unknown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Unknown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Convert Currency
        
        if(FirstCountry.getSelectedIndex()==0 || SecondCountry.getSelectedIndex()==0 || T1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please select countries and input the amount","ERROR MESSAGE",JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        double AmountToChange = Double.parseDouble(T1.getText());
        
        double AmountInPounds = 0.0;
        
        double AmountChanged=0.0;
        switch(FirstCountry.getSelectedItem().toString())
        {
           case "United States": AmountInPounds = AmountToChange/US_Dollar;break;
           case "France": AmountInPounds = AmountToChange/France_Euro;break;
           case "United Kingdom": AmountInPounds = AmountToChange/UK_Pound;break;
           case "India" : AmountInPounds = AmountToChange/Indian_Rupees;break;
           case "Pakistan": AmountInPounds = AmountToChange/ Pakistani_Rupees;break;    
           case "Japan": AmountInPounds = AmountToChange/Japanese_Yen;break;
           case "Canada": AmountInPounds = AmountToChange/Canadian_Dollar;break;
           case "Russia": AmountInPounds = AmountToChange/Russian_Ruble;break;
           default: AmountInPounds =0.0;
        }
        
        switch(SecondCountry.getSelectedItem().toString())
        {
            case "United States": AmountChanged = AmountInPounds * US_Dollar;break;
            case "France": AmountChanged = AmountInPounds * France_Euro;break;
            case "United Kingdom": AmountChanged = AmountInPounds * UK_Pound;break;
            case "India" : AmountChanged = AmountInPounds * Indian_Rupees;break;
            case "Pakistan": AmountChanged = AmountInPounds * Pakistani_Rupees;break; 
            case "Japan": AmountChanged = AmountInPounds * Japanese_Yen;break;
            case "Canada": AmountChanged = AmountInPounds * Canadian_Dollar;break;
            case "Russia": AmountChanged = AmountInPounds * Russian_Ruble;break;
            default: AmountChanged = AmountInPounds * 0.0;
        }
        
        String Value = String.format("%.2f",AmountChanged);
        T2.setText(Value);



// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FirstCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FirstCountryItemStateChanged
       
        int position= FirstCountry.getSelectedIndex();
        FirstCurrencyUnit.setText(CurrencyUnits[position]);
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstCountryItemStateChanged

    private void SecondCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SecondCountryItemStateChanged
      
        int position= SecondCountry.getSelectedIndex();
        SecondCurrencyUnit.setText(CurrencyUnits[position]);
    }//GEN-LAST:event_SecondCountryItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        FirstCountry.setSelectedIndex(0);
        SecondCountry.setSelectedIndex(0);
        T1.setText(null);
        T2.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FirstCountry;
    private javax.swing.JLabel FirstCurrencyUnit;
    private javax.swing.JComboBox<String> SecondCountry;
    private javax.swing.JLabel SecondCurrencyUnit;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JPanel Unknown;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
